name: Application Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  APPLICATION_VERSION: 0.1.${{ github.run_number }}
  TF_VAR_application_name: ${{ github.event.repository.name }}
  TF_VAR_operations_assume_role: ${{ secrets.OPERATIONS_ROLE_TO_ASSUME }}

jobs:
  setup-ecr:
    name: Setup ECR Repository
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deployment/ecr
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true

      - uses: actions/github-script@v5
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outputs.stdout }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Get ECR Repository URL
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: ecr-repository-url
        run: terraform output -no-color -raw repository_url

      - name: Write ECR repository URL to artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: ecr-artifact
        run: echo "${{ steps.ecr-repository-url.outputs.stdout }}" > ${{ github.workspace }}/ecr-url.txt

      - name: Upload ecr repository url
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v2.2.1
        with:
          name: ecr
          path: ${{ github.workspace }}/ecr-url.txt
          if-no-files-found: error

  test:
    name: Run Tests and Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Run Tests
      - run: npm test

      - name: Upload file report files as an artifact
        if: success()
        uses: actions/upload-artifact@v2.2.4
        with:
          name: reports
          path: reports/
          retention-days: 1
