name: Production Workflow

on:
  workflow_run:
    workflows:
      - "Application Build"
    types:
      - completed

jobs:
  deploy-production:
    needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello from prod workflow"

      - name: Echo Output
        run: echo "Output from Application Build: ${{ needs.test.outputs.my-output }}"
