name: Production Workflow

on:
  release:
    types:
      - created
    branches:
      - release/*

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This will deploy to Production environment"
